# -*- coding: utf-8 -*-
"""house_price_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ycQmCM_a0dQXa3LFZ2EzcOtyFuBTr9r
"""

import streamlit as st
import numpy as np
import pickle

# 加载训练好的模型（提前用 Scikit-learn 训练并保存）
with open("/Users/phoebe_private/Downloads/house_price_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("🏠 房价预测应用")

# 用户输入
sqft = st.slider("房屋面积（平方英尺）", 500, 5000, 1500)
bedrooms = st.selectbox("卧室数量", [1, 2, 3, 4, 5])
bathrooms = st.selectbox("浴室数量", [1, 2, 3, 4])

# 预测按钮
if st.button("预测价格"):
    features = np.array([[sqft, bedrooms, bathrooms]])
    price = model.predict(features)[0]
    st.success(f"🏡 预测房价: ${price:,.2f}")